package com.ventas.views;

import com.ventas.views.admin.ProfileView;
import com.ventas.views.admin.SaleView;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author tlser
 */
public class AdminView extends javax.swing.JFrame {

    private final Content content = new Content("admin.jpg");
    private final String userId;
     
    public AdminView(String userId) {
        setContentPane(content);
        setResizable(false);
        initComponents();
        this.userId = userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnModifyProfile = new javax.swing.JLabel();
        btnListSales = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnModifyProfile.setBackground(new java.awt.Color(255, 255, 255));
        btnModifyProfile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnModifyProfile.setForeground(new java.awt.Color(51, 51, 51));
        btnModifyProfile.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnModifyProfile.setText("Modificar perfil");
        btnModifyProfile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnModifyProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModifyProfile.setOpaque(true);
        btnModifyProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModifyProfileMouseClicked(evt);
            }
        });

        btnListSales.setBackground(new java.awt.Color(153, 255, 153));
        btnListSales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListSales.setForeground(new java.awt.Color(255, 255, 255));
        btnListSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnListSales.setText("Ventas realizadas");
        btnListSales.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0), new java.awt.Color(0, 153, 0)));
        btnListSales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListSales.setOpaque(true);
        btnListSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListSalesMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Vivaldi", 3, 45)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Store");

        jLabel2.setFont(new java.awt.Font("Vivaldi", 3, 45)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manment");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnModifyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListSales, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(btnListSales, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnModifyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModifyProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifyProfileMouseClicked
        new ProfileView(userId).start();
        this.dispose();
    }//GEN-LAST:event_btnModifyProfileMouseClicked

    private void btnListSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListSalesMouseClicked
        new SaleView().start();
        this.dispose();
    }//GEN-LAST:event_btnListSalesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnListSales;
    private javax.swing.JLabel btnModifyProfile;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

    public void start() {
        setLocationRelativeTo(null);
        setTitle("Perfil de administrador");
        setVisible(true);
    }
}
