package com.ventas.views.catalog;

import com.ventas.controllers.CatalogController;
import com.ventas.util.Message;
import com.ventas.views.ClientView;
import com.ventas.views.Content;
import com.ventas.views.delivery.DeliveryView;
import com.ventas.views.delivery.ShipmentView;
import java.util.Vector;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tlser
 */
public class CatalogMens extends javax.swing.JFrame implements CatalogView {

    private final CatalogController controller;
    private final String userId;
    
    Content content = new Content("mens-catalog.jpg");

    public CatalogMens(String userId) {
        this.setContentPane(content);
        setResizable(false);
        initComponents();
        
        this.userId = userId;
        
        controller = new CatalogController(this);
        
        //Populate list
        controller.showCatalog("Hombres");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listMens = new javax.swing.JList<>();
        jLabel28 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnSale = new javax.swing.JButton();
        txtQty = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 397));

        listMens.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        listMens.setForeground(new java.awt.Color(102, 102, 102));
        listMens.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listMens);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("CATALOGO DE HOMBRES");

        btnCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCancel.setText("OMITIR");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnSale.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSale.setText("REALIZAR COMPRA");
        btnSale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleActionPerformed(evt);
            }
        });

        txtQty.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtQty.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQty))
                .addGap(59, 59, 59))
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel28)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSale)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        new ClientView(userId).start();
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleActionPerformed
        if (listMens.getSelectedValue() != null) {
          controller.doSale(listMens.getSelectedValue(), txtQty.getValue().toString());
       } else {
           onError("Debe seleccionar un producto");
       }
    }//GEN-LAST:event_btnSaleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSale;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listMens;
    private javax.swing.JSpinner txtQty;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void onSuccess() {
        int result = Message.question(this, "Compra exitosa\n¿Desea recibir su pedido a domicilio?");
        
        if (result == 0) {
            int delivery = Message.question(this, "¿Envio local?");
            
            if (delivery == 0) {
                new DeliveryView(userId).start();
                this.dispose();
            } else {
                new ShipmentView(userId).start();
                this.dispose();
            }
        }
    }
    
    @Override
    public void onError(String message) {
        Message.error(this, message);
    }
    
    @Override
    public void showCatalog(Vector<String> catalog) {
        listMens.setListData(catalog);
    }
    
    public void start() {
        setLocationRelativeTo(null);
        setTitle("Catalogo de hombres");
        setVisible(true);
    }
}
